name: Test and Coverage
run-name: Running Tests and Generating Coverage Reports
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: './front/package-lock.json'

      - name: Install dependencies
        run: npm ci

      # Install Chrome browser for Karma
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # Run tests with coverage
      - name: Run tests and generate coverage
        run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadless

      # Upload coverage report as artifact
      - name: Upload frontend coverage
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: front/coverage/
          retention-days: 7

  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Run tests and generate JaCoCo report
      - name: Run tests with Maven
        run: mvn clean test jacoco:report

      # Upload JaCoCo report as artifact
      - name: Upload backend coverage
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: back/target/site/jacoco/
          retention-days: 7